# -*- coding: utf-8 -*-
"""stemming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlFkR1vL6objOW2W6YYYqDmt7m4Qo6qO
"""

!python -m nltk.downloader punkt

pip install nltk

import nltk
from nltk.corpus import wordnet
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('wordnet')

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()


text = "fasting"


words = nltk.word_tokenize(text)


stemmed_words = [stemmer.stem(word) for word in words]


lemmatized_words = [lemmatizer.lemmatize(word, pos='v') for word in words]

print("Original words:", words)
print("Stemmed words:", stemmed_words)
print("Lemmatized words:", lemmatized_words)

